# Generated by Django 2.0.6 on 2018-06-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='store',
            name='url_identifying_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
