# Generated by Django 2.0.6 on 2018-06-26 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_auto_20180624_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=20)),
                ('display_order', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.Store')),
            ],
        ),
    ]
