# Generated by Django 2.0.6 on 2018-06-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0007_storemenuoption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreMenuOption',
            new_name='StoreCategory',
        ),
    ]
