# Generated by Django 2.0.6 on 2018-06-29 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0008_auto_20180626_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.Product')),
                ('store_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.StoreCategory')),
            ],
        ),
    ]
