# Generated by Django 2.0.6 on 2018-08-14 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0012_auto_20180813_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.Product')),
            ],
        ),
    ]
