# Generated by Django 2.0.6 on 2018-08-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0013_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('IC', 'In-Cart'), ('OR', 'Ordered'), ('CM', 'Completed')], default='IC', max_length=2),
        ),
    ]
