# Generated by Django 2.0.6 on 2018-08-24 22:40

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('ordering', '0014_order_order_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Shopper',
        ),
    ]
