# Generated by Django 2.0.6 on 2018-09-01 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0016_auto_20180824_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
