# Generated by Django 2.1.3 on 2019-03-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0018_auto_20180901_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(max_length=50)),
                ('secondary_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date ordered'),
        ),
    ]
