# Generated by Django 2.1.7 on 2019-03-03 22:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0019_auto_20190303_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestyle',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='storestyle',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#FF00FF', max_length=18),
        ),
    ]
