# Generated by Django 2.1.7 on 2019-03-03 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0020_auto_20190303_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='style',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='ordering.StoreStyle'),
        ),
        migrations.AddField(
            model_name='storestyle',
            name='name',
            field=models.CharField(default='Color Style', max_length=200),
        ),
    ]
