# Generated by Django 2.1.7 on 2019-03-05 02:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0021_auto_20190303_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestyle',
            name='secondary_selected_color',
            field=colorfield.fields.ColorField(default='#a9a9a9', max_length=18),
        ),
    ]
