# Generated by Django 2.1.7 on 2019-03-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0022_storestyle_secondary_selected_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storestyle',
            old_name='secondary_selected_color',
            new_name='tertiary_color',
        ),
    ]
